version: '2'
services:
  web:
    build: .
    ports:
     - "8000:8000"
    depends_on:
     - redis
    volumes:
      - ./data:/app/data
      - ./model_artifacts:/app/model_artifacts
      - ./notebooks:/app/notebooks
  redis:
    image: redis